In [1]:
import yfinance as yf

tickers = yf.Tickers('msft aapl goog')
# ^ returns a named tuple of Ticker objects

# access each ticker using (example)
tickers.tickers.MSFT.info
tickers.tickers.AAPL.history(period="1mo")
tickers.tickers.GOOG.actions

AttributeError: 'dict' object has no attribute 'MSFT'

In [2]:
data = yf.download("SPY AAPL", start="2017-01-01", end="2017-04-30")

[*********************100%***********************]  2 of 2 completed

In [5]:
data = yf.download(  # or pdr.get_data_yahoo(...
        # tickers list or string as well
        tickers = "SPY AAPL MSFT",

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "ytd",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1mo",

        # Whether to ignore timezone when aligning ticker data from 
        # different timezones. Default is True. False may be useful for 
        # minute/hourly data.
        ignore_tz = False,

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'ticker',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )
data

[*********************100%***********************]  3 of 3 completed

                  MSFT                                                   \
                  Open        High         Low       Close       Volume
Date
2022-02-01  307.528421  312.194689  268.999429  296.016296  697050600.0
2022-02-04         NaN         NaN         NaN         NaN          NaN
2022-02-16         NaN         NaN         NaN         NaN          NaN
2022-03-01  294.255629  313.664209  268.046631  306.079468  734334200.0
2022-03-18         NaN         NaN         NaN         NaN          NaN
2022-04-01  307.131787  312.830250  268.046623  275.512207  627343400.0
2022-05-01  275.700853  288.775585  244.657092  269.903107  742902000.0
2022-05-06         NaN         NaN         NaN         NaN          NaN
2022-05-18         NaN         NaN         NaN         NaN          NaN
2022-06-01  273.845383  276.323116  240.321199  255.565781  621372300.0
2022-06-17         NaN         NaN         NaN         NaN          NaN
2022-07-01  255.127976  280.611901  244.729403  279.358093  534891800.0
2022-08-01  276.452446  292.731900  259.376912  260.182922  477157600.0
2022-08-05         NaN         NaN         NaN         NaN          NaN
2022-08-17         NaN         NaN         NaN         NaN          NaN
2022-09-01  258.142502  266.698407  232.075963  232.245483  575586600.0
2022-09-16         NaN         NaN         NaN         NaN          NaN
2022-10-01  234.748442  250.334508  218.514194  231.477661  671225100.0
2022-11-01  233.940718  254.612457  212.830198  254.422989  615255600.0
2022-11-04         NaN         NaN         NaN         NaN          NaN
2022-11-16         NaN         NaN         NaN         NaN          NaN
2022-12-01  253.869995  263.920013  242.210007  244.690002  387085100.0
2022-12-16  248.550003  249.820007  243.550003  244.690002   86101994.0

                  AAPL                                                    \
                  Open        High         Low       Close        Volume
Date
2022-02-01  173.005923  175.630690  151.122931  164.167221  1.627516e+09
2022-02-04         NaN         NaN         NaN         NaN           NaN
2022-02-16         NaN         NaN         NaN         NaN           NaN
2022-03-01  163.958265  178.801121  149.424026  173.823639  2.180800e+09
2022-03-18         NaN         NaN         NaN         NaN           NaN
2022-04-01  173.246238  177.686159  154.680237  156.940002  1.687796e+09
2022-05-01  156.004245  165.730233  132.012776  148.169678  2.401040e+09
2022-05-06         NaN         NaN         NaN         NaN           NaN
2022-05-18         NaN         NaN         NaN         NaN           NaN
2022-06-01  149.444158  151.278574  128.647591  136.304245  1.749100e+09
2022-06-17         NaN         NaN         NaN         NaN           NaN
2022-07-01  135.626301  163.132413  135.247467  162.015808  1.447125e+09
2022-08-01  160.520381  175.614342  156.662154  156.741913  1.510240e+09
2022-08-05         NaN         NaN         NaN         NaN           NaN
2022-08-17         NaN         NaN         NaN         NaN           NaN
2022-09-01  156.380578  163.987953  137.771449  137.971115  2.084723e+09
2022-09-16         NaN         NaN         NaN         NaN           NaN
2022-10-01  137.981112  157.239158  134.147460  153.086044  1.868140e+09
2022-11-01  154.823179  155.192561  134.157462  147.784851  1.724691e+09
2022-11-04         NaN         NaN         NaN         NaN           NaN
2022-11-16         NaN         NaN         NaN         NaN           NaN
2022-12-01  148.210007  150.919998  133.729996  134.509995  9.837964e+08
2022-12-16  136.684998  137.649994  133.729996  134.509995  1.598057e+08

                   SPY
                  Open        High         Low       Close        Volume
Date
2022-02-01  443.485205  450.806433  404.084437  429.659515  2.297975e+09
2022-02-04         NaN         NaN         NaN         NaN           NaN
2022-02-16         NaN         NaN         NaN         NaN           NaN
2022-03-01  428.094844  454.693324  408.492842  444.429840  2.380930e+09
2022-03-18         NaN         NaN         NaN         NaN           NaN
2022-04-01  447.458987  451.920635  405.902378  406.682190  1.856757e+09
2022-05-01  406.751304  424.114261  375.628272  407.600189  2.418478e+09
2022-05-06         NaN         NaN         NaN         NaN           NaN
2022-05-18         NaN         NaN         NaN         NaN           NaN
2022-06-01  409.811307  412.051997  357.495392  372.380737  1.958612e+09
2022-06-17         NaN         NaN         NaN         NaN           NaN
2022-07-01  373.305257  409.460035  367.832979  408.429016  1.437748e+09
2022-08-01  405.613566  427.998416  391.625539  391.764313  1.443394e+09
2022-08-05         NaN         NaN         NaN         NaN           NaN
2022-08-17         NaN         NaN         NaN         NaN           NaN
2022-09-01  389.494109  408.171264  353.953969  354.092743  1.998909e+09
2022-09-16         NaN         NaN         NaN         NaN           NaN
2022-10-01  359.429476  387.739478  346.518761  384.444611  2.024732e+09
2022-11-01  388.356665  405.816467  367.104251  405.816467  1.745985e+09
2022-11-04         NaN         NaN         NaN         NaN           NaN
2022-11-16         NaN         NaN         NaN         NaN           NaN
2022-12-01  406.901506  408.613645  379.298279  381.518066  1.069737e+09
2022-12-16         NaN         NaN         NaN         NaN           NaN